# ------------------------------
# IECE_GATEWAY_IP comes from .env file
# that exists in same directory as this script
# 
services:
  iece_gateway:
    build: ../iece-gateway
    ports:
      - "443:443"
    volumes:
      - ../iece-gateway/default.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/certs
    depends_on:
      - iece_auth
    networks:
      - iece_network

  iece_auth:
    env_file:
      - ../iece-auth/.env
    build: ../iece-auth
    ports:
      - "8000:8000"
    volumes:
      - ../iece-auth:/app
    expose:
      - "8000"
    networks:
      - iece_network

  iece_church:
    env_file:
      - ../iece-church/.env
    build: ../iece-church
    ports:
      - "8001:8000"
    volumes:
      - ../iece-church:/app
    depends_on:
      - iece_auth
    expose:
      - "8001"
    networks:
      - iece_network

  jubilo_meilisearch:
    env_file:
      - ../jubilo-music/.env
    image: getmeili/meilisearch:v1.10
    volumes:
      - ../jubilo-music/meili_data:/meili_data
    ports:
      - "7700:7700"
    networks:
      - iece_network

  jubilo_music_db:
    image: postgres:16
    environment:
        POSTGRES_DB: jubilo_music
        POSTGRES_USER: jubilo_music_user
        POSTGRES_PASSWORD: jubilo_music_password
    ports:
      - "5432:5432"
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U jubilo_music -d jubilo_music || exit 1"]
        interval: 5s
        timeout: 5s
        retries: 5
    networks:
      - iece_network

  jubilo_music:
    env_file:
      - ../jubilo-music/.env
    build: ../jubilo-music
    ports:
      - "8002:8000"
    volumes:
      - ../jubilo-music:/app
    depends_on:
      jubilo_music_db:
        condition: service_healthy
      iece_auth:
        condition: service_started
    expose:
      - "8002"
    networks:
      - iece_network

  # iece_report:
  #   build: ./iece_report
  #   env_file:
  #     - ./iece_report/.env
  #   image: iece_report
  #   networks:
  #     - iece_network
  #   volumes:
  #     - ./iece_report/output:/app/output
  #   depends_on:
  #     - iece_auth
  #     - iece_church
  #     - iece_gateway
networks:
  iece_network:
