# ------------------------------
# JUBILO_GATEWAY_IP comes from .env file
# that exists in same directory as this script
# 
services:
  jubilo_gateway:
    build: ../jubilo-gateway
    ports:
      - "443:443"
    volumes:
      - ../jubilo-gateway/default.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/certs
    depends_on:
      - jubilo_auth
      - jubilo_music
    networks:
      - jubilo_network

  jubilo_mailpit:
    image: axllent/mailpit
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Web UI + API
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8025/api/v1/info"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s
    networks:
      - jubilo_network

  jubilo_redis:
    image: redis:7-alpine
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s    
    networks:
      - jubilo_network

  jubilo_auth_db:
    image: postgres:16
    environment:
        POSTGRES_DB: jubilo_auth
        POSTGRES_USER: jubilo_auth_user
        POSTGRES_PASSWORD: jubilo_auth_password
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U jubilo_auth_user -d jubilo_auth || exit 1"]
        interval: 5s
        timeout: 5s
        retries: 5
    ports:
      - "5432:5432"
    networks:
      - jubilo_network

  jubilo_auth:
    env_file:
      - ../jubilo-auth/.env
    build: ../jubilo-auth
    ports:
      - "8000:8000"
    volumes:
      - ../jubilo-auth:/app
    expose:
      - "8000"
    depends_on:
      jubilo_auth_db:
        condition: service_healthy
      jubilo_redis:
        condition: service_healthy
      jubilo_mailpit:
        condition: service_healthy
    networks:
      jubilo_network:
          aliases:
            - jubilo-auth # Because django does not allow underscores in hostnames (ALLOWED_HOSTS), we need to add an alias for the service name with a hyphen instead of an underscore.

  iece_church:
    env_file:
      - ../iece-church/.env
    build: ../iece-church
    ports:
      - "8001:8000"
    volumes:
      - ../iece-church:/app
    depends_on:
      - jubilo_auth
    expose:
      - "8001"
    networks:
      - jubilo_network

  jubilo_meilisearch:
    env_file:
      - ../jubilo-music/.env
    image: getmeili/meilisearch:v1.10
    volumes:
      - ../jubilo-music/meili_data:/meili_data
    ports:
      - "7700:7700"
    networks:
      - jubilo_network

  jubilo_music_db:
    image: postgres:16
    environment:
        POSTGRES_DB: jubilo_music
        POSTGRES_USER: jubilo_music_user
        POSTGRES_PASSWORD: jubilo_music_password
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U jubilo_music_user -d jubilo_music || exit 1"]
        interval: 5s
        timeout: 5s
        retries: 5
    ports:
      - "5433:5432"
    networks:
      - jubilo_network

  jubilo_music:
    env_file:
      - ../jubilo-music/.env
    build: ../jubilo-music
    ports:
      - "8002:8000"
    volumes:
      - ../jubilo-music:/app
    depends_on:
      jubilo_music_db:
        condition: service_healthy
      jubilo_auth:
        condition: service_started
      jubilo_redis:
        condition: service_healthy
    expose:
      - "8002"
    networks:
      - jubilo_network

  # iece_report:
  #   build: ./iece_report
  #   env_file:
  #     - ./iece_report/.env
  #   image: iece_report
  #   networks:
  #     - jubilo_network
  #   volumes:
  #     - ./iece_report/output:/app/output
  #   depends_on:
  #     - jubilo_auth
  #     - iece_church
  #     - jubilo_gateway
networks:
  jubilo_network:
