#!/usr/bin/env python3

import argparse
from services.docker import (
	docker_generate_service_tokens,
	docker_generate_jubilo_infrastructure_env_files,
	docker_get_host_ip,
	docker_generate_ssl_certs,
	docker_generate_auth_service_env_file,
	docker_generate_church_service_env_file,
	docker_generate_music_service_env_file,
	docker_generate_jubilo_mobile_env_file,
	docker_build,
	docker_start,
	docker_stop,
	docker_down,
	docker_run,
	generate_token,
)

import time
import requests
from pathlib import Path
import os
import shutil

def setup_meilisearch_data_directory():
	print("setup_meilisearch_data_directory - START")
	path = "../meili_data"
	
	if os.path.exists(path):
		shutil.rmtree(path)

	os.makedirs(path, exist_ok=True)

	print("setup_meilisearch_data_directory - END")

def dev_setup(service_name_list=None):
	print("Setting up development environment...")

	SUPERUSER_EMAIL = "su1@gmail.com"
	SUPERUSER_PASSWORD = "su1"
	IBG_USER_EMAIL = "ib@gmail.com"
	IBG_USER_PASSWORD = "testpassword"

	docker_down([])

	docker_host_ip = docker_get_host_ip()
	print(f"Docker host IP address: {docker_host_ip}")

	docker_generate_jubilo_infrastructure_env_files(docker_host_ip)

	docker_generate_ssl_certs(docker_host_ip)

	#------------------------------
	# CHURCH SERVICE
	#
	church_service_tokens = docker_generate_service_tokens()

	print(f"CHURCH Service:")
	print(f"  Client ID     : {church_service_tokens['client_id']}")
	print(f"  Client Secret : {church_service_tokens['client_secret']}")

	docker_generate_church_service_env_file(docker_host_ip, church_service_tokens)

	#------------------------------
	# MUSIC SERVICE
	#
	jubilo_music_service_tokens = docker_generate_service_tokens()

	print(f"JUBILO MUSIC Service:")
	print(f"  Client ID     : {jubilo_music_service_tokens['client_id']}")
	print(f"  Client Secret : {jubilo_music_service_tokens['client_secret']}")

	jubilo_music_service_tokens['JUBILO_MEILISEARCH_MASTER_KEY'] = generate_token(32)
	jubilo_music_service_tokens['JUBILO_MEILISEARCH_URL'] = f"http://jubilo_meilisearch:7700"

	docker_generate_music_service_env_file(docker_host_ip, jubilo_music_service_tokens)

	#------------------------------
	# JUBILO MOBILE SERVICE
	#
	jubilo_mobile_tokens = docker_generate_service_tokens()

	print(f"JUBILO MOBILE Service:")
	print(f"  Client ID     : {jubilo_mobile_tokens['client_id']}")
	print(f"  Client Secret : {jubilo_mobile_tokens['client_secret']}")

	docker_generate_jubilo_mobile_env_file(docker_host_ip, jubilo_mobile_tokens)

	#------------------------------
	# AUTH SERVICE
	#
	auth_service_tokens = docker_generate_service_tokens()

	auth_service_tokens['DJANGO_SUPERUSER_EMAIL'] = SUPERUSER_EMAIL
	auth_service_tokens['DJANGO_SUPERUSER_PASSWORD'] = SUPERUSER_PASSWORD
	auth_service_tokens['DJANGO_SUPERUSER_FIRST_NAME'] = 'su1'
	auth_service_tokens['DJANGO_SUPERUSER_LAST_NAME'] = 'su1'

	print(f"AUTH Service:")
	print(f"  Client ID                   : {auth_service_tokens['client_id']}")
	print(f"  Client Secret               : {auth_service_tokens['client_secret']}")
	print(f"  DJANGO_SUPERUSER_EMAIL      : {auth_service_tokens['DJANGO_SUPERUSER_EMAIL']}")
	print(f"  DJANGO_SUPERUSER_PASSWORD   : {auth_service_tokens['DJANGO_SUPERUSER_PASSWORD']}")
	print(f"  DJANGO_SUPERUSER_FIRST_NAME : {auth_service_tokens['DJANGO_SUPERUSER_FIRST_NAME']}")
	print(f"  DJANGO_SUPERUSER_LAST_NAME  : {auth_service_tokens['DJANGO_SUPERUSER_LAST_NAME']}")

	docker_generate_auth_service_env_file(docker_host_ip, {
		"auth": auth_service_tokens,
		"church": church_service_tokens,
		"jubilo_mobile": jubilo_mobile_tokens,
		"jubilo_music": jubilo_music_service_tokens,
	})

	docker_build([])

	# ------------------------------
	# NOTE: Because we are using Docker, the container itself is the environment so a virtual environment is not necessary.
	#       For services that use Python, the Python interpreter would be isolated inside the container, so we don't need to worry about activating a virtual environment like we would in a non-Dockerized setup.
	#       Dependencies are installed inside the Docker container as part of the Dockerfile, so we just need to make sure that the Docker container is built and running.
	#       Service specific scripts need to run inside the container, so we can use "docker compose exec" or "docker compose run --rm" command to run them.
	# 

	docker_run("auth", "python -m scripts.auth_dev_setup")

	#------------------------------
	# Since gateway container depends on auth service, we can start
	# the gateway container which will automatically start the auth service container as well. 
	# This way we ensure that the auth service is fully up and running before we try to acquire
	# a token for the auth service superuser, which is necessary for running the rest of the
	# setup scripts for the other services since they need to make authenticated requests to the auth service.
	# 
	docker_start(["gateway"])

	#------------------------------
	# Wait for the services to be fully up and running before
	#    Trying to acquire a token for the auth service superuser
	#    Making a jubilo music service request using the auth service superuser token to verify that everything is working end to end.
	# 
	# time.sleep(5)

	#------------------------------
	# Aquiring token for auth service superuser using credentials:
	#    auth_service_tokens['DJANGO_SUPERUSER_EMAIL']
	#    auth_service_tokens['DJANGO_SUPERUSER_PASSWORD']
	# But using the registered Postman application client_id which uses the Password Grant flow.
	# The Password Grant flow is the most straightforward way to acquire a token for the superuser
	# since we have their username and password, and we don't have to worry about setting up a separate
	# client credentials flow or manually creating a token in the database.
	# 
	# NOTE: Only for development and testing purposes.
	# In production, you would want to use a more secure flow and not have the superuser
	# credentials hardcoded or easily accessible.
	# 
	superuser_access_token = None

	CA_CERT = str(Path(__file__).parent / "rootCA.pem")

	print(f"CA_CERT path: {CA_CERT}")

	while not superuser_access_token:
		try:
			response = requests.post(f"https://{docker_host_ip}/auth/o/token/",
				data={
					"grant_type": "password",
					"username": SUPERUSER_EMAIL,
					"password": SUPERUSER_PASSWORD,
					"client_id": 'lxxIzlAW1Ge0JXshCfpCYG0EGKGedhKSRnzpJDVn', # TODO: Don't use jubilo_postman client_id
					"scope": "auth music"
				},
				verify=CA_CERT,
				timeout=5)
			
			response.raise_for_status()

			json_data = response.json()
			if "access_token" not in json_data:
				raise ValueError(f"Response JSON does not contain 'access_token': {json_data}")
			superuser_access_token = json_data.get("access_token")
		except Exception as e:
			RETRY_SECONDS = 1
			print(f"Failed to acquire access token for auth service superuser. Error: {e}")
			print(f"Retrying in {RETRY_SECONDS} seconds...")
			time.sleep(RETRY_SECONDS)

	print(f"Acquired access token for auth service superuser: {superuser_access_token}")

	#------------------------------
	# Inviting a user with member privileges.
	# 
	try:
		response = requests.post(f"https://{docker_host_ip}/auth/invitation",
			json={
				"email": IBG_USER_EMAIL,
				"first_name": "Ismael",
				"last_name": "Baez",
				"roles": [
					{
						"service": "music",
						"role": "music_member"
					}
				]
			},
			headers={
				"Authorization": f"Bearer {superuser_access_token}"
			},
			verify=CA_CERT,
			timeout=5)
		
		response.raise_for_status()
	except Exception as e:
		print(f"Failed to invite user. Error: {e}")
		print(f"Response status code: {response.status_code}")
		print(f"Response text: {response.text}")
		return

	#------------------------------
	# Listing invitations in order to get the member user's invitation code which is necessary for accepting the invitation and creating the member user.
	# 
	invitation_code = None
	try:
		response = requests.get(f"https://{docker_host_ip}/auth/invitation",
			headers={
				"Authorization": f"Bearer {superuser_access_token}"
			},
			verify=CA_CERT,
			timeout=5)
		
		response.raise_for_status()
		invitation_code = response.json()[0]['code']
		print(f"Invitation code for member user: {invitation_code}")
	except Exception as e:
		print(f"Failed to list invitations. Error: {e}")
		print(f"Response status code: {response.status_code}")
		print(f"Response text: {response.text}")
		return

	#------------------------------
	# Accepting invitation for auth service member user.
	# 
	try:
		response = requests.post(f"https://{docker_host_ip}/auth/invitation/accept",
			data={
				"code": invitation_code,
				"password": IBG_USER_PASSWORD
			},
			verify=CA_CERT,
			timeout=5)
		
		response.raise_for_status()
	except Exception as e:
		print(f"Failed to accept invitation. Error: {e}")
		print(f"Response status code: {response.status_code}")
		print(f"Response text: {response.text}")
		return

	#------------------------------
	# Acquiring access token for auth service member user.
	# 
	member_access_token = None
	try:
		response = requests.post(f"https://{docker_host_ip}/auth/o/token/",
			data={
				"grant_type": "password",
				"username": IBG_USER_EMAIL,
				"password": IBG_USER_PASSWORD,
				"client_id": 'lxxIzlAW1Ge0JXshCfpCYG0EGKGedhKSRnzpJDVn', # TODO: Don't use jubilo_postman client_id
				"scope": "auth music"
			},
			verify=CA_CERT,
			timeout=5)
		
		response.raise_for_status()

		json_data = response.json()
		if "access_token" not in json_data:
			raise ValueError(f"Response JSON does not contain 'access_token': {json_data}")
		member_access_token = json_data.get("access_token")
	except Exception as e:
		print(f"Failed to acquire access token for auth service member. Error: {e}")
		return

	print(f"Acquired access token for auth service member: {member_access_token}")

	# ------------------------------
	# Clear and setup jubilo_music service search index
	# 
	setup_meilisearch_data_directory()

	docker_start(["meilisearch"])
	docker_start(["music"])

	docker_run("music", "python -m scripts.music_dev_setup --access-token {}".format(superuser_access_token))

	url = f"https://{docker_host_ip}/api/music/artist"

	print(f"Making request to {url}")

	response = requests.get(url,
		headers={
			"Authorization": f"Bearer {superuser_access_token}"
		},
		verify=CA_CERT,
		timeout=5)
	
	print(f"ArtistList request to music service response: {response.status_code} - {response.text}")

	list = response.json()

	for artist in list:
		print(f"Artist: {artist['artist_name']}")

	url = f"https://{docker_host_ip}/api/music/topic"

	print(f"Making request to {url}")

	response = requests.get(url,
		headers={
			"Authorization": f"Bearer {superuser_access_token}"
		},
		verify=CA_CERT,
		timeout=5)
	
	print(f"TopicList request to music service response: {response.status_code} - {response.text}")

	list = response.json()

	for topic in list:
		print(f"Topic ({topic['id']}): {topic['topic_key']}")

def dev_test_jubilo_auth():
	print("Running tests for jubilo_auth service")

	#------------------------------
	# Running a specific invitation test for auth service
	# 
	# docker_run("auth", "python manage.py test jubilo_auth.accounts.tests.invitation.test_invitation.InvitationTests.test_token_exchange_succeeds_with_correct_verifier")

	#------------------------------
	# Running all invitation tests for auth service
	# 
	# docker_run("auth", "python manage.py test jubilo_auth.accounts.tests.invitation.test_invitation")

	#------------------------------
	# Running all tests
	# 
	docker_run("auth", "python manage.py test jubilo_auth.accounts.tests")


def dev_test_jubilo_music():
	print("Running tests for jubilo_music service")

	#------------------------------
	# Running a specific artist test
	# 
	# docker_run("music", "python manage.py test music.tests.artist.test_artist.ArtistTests.test_delete_artist_that_has_no_albums_succeeds")

	#------------------------------
	# Running all artist tests
	# 
	# docker_run("music", "python manage.py test music.tests.artist.test_artist")



	#------------------------------
	# Running a specific album test
	# 
	# docker_run("music", "python manage.py test music.tests.album.test_album.AlbumTests.test_update_album_with_category_field_from_album_to_single_fails_if_album_has_multiple_hymns")

	#------------------------------
	# Running all album tests
	# 
	# docker_run("music", "python manage.py test music.tests.album.test_album")



	# ------------------------------
	# HYMN TESTS
	#

	#------------------------------
	# Running a specific hymn test
	# 
	# docker_run("music", "python manage.py test music.tests.hymn.test_hymn.HymnTests.test_retrieve_album_does_not_include_deleted_hymns")

	#------------------------------
	# Running all hymn tests
	# 
	# docker_run("music", "python manage.py test music.tests.hymn.test_hymn")


	# ------------------------------
	# TOPIC TESTS
	#

	#------------------------------
	# Running a specific topic test
	# 
	# docker_run("music", "python manage.py test music.tests.topic.test_topic.TopicTests.test_retrieve_archived_topic_does_not_find_active_topic")

	#------------------------------
	# Running all topic tests
	# 
	# docker_run("music", "python manage.py test music.tests.topic.test_topic")



	# ------------------------------
	# HYMN-TOPIC TESTS
	#

	#------------------------------
	# Running a specific hymn topic test
	# 
	# docker_run("music", "python manage.py test music.tests.hymn_topic.test_hymn_topic.HymnTopicTests.test_delete_hymn_topic_already_deleted")

	#------------------------------
	# Running all hymn topic tests
	# 
	# docker_run("music", "python manage.py test music.tests.hymn_topic.test_hymn_topic")



	# ------------------------------
	# PLAYLIST TESTS
	#

	#------------------------------
	# Running a specific playlist test
	# 
	# docker_run("music", "python manage.py test music.tests.playlist.test_playlist.PlaylistTests.test_update_playlist_cannot_update_public_playlist_of_another_user")

	#------------------------------
	# Running all playlist tests
	# 
	# docker_run("music", "python manage.py test music.tests.playlist.test_playlist")



	# ------------------------------
	# PLAYLIST HYMN TESTS
	#

	#------------------------------
	# Running a specific playlist hymn test
	# 
	# docker_run("music", "python manage.py test music.tests.playlist_hymn.test_playlist_hymn.PlaylistHymnTests.test_delete_playlist_hymn_same_playlist_hymn_multiple_delete")

	#------------------------------
	# Running all playlist hymn tests
	# 
	# docker_run("music", "python manage.py test music.tests.playlist_hymn.test_playlist_hymn")



	# ------------------------------
	# HYMN LYRIC TESTS
	#

	#------------------------------
	# Running a specific hymn lyric test
	# 
	# docker_run("music", "python manage.py test music.tests.hymn_lyric.test_hymn_lyric.HymnLyricTests.test_create_hymn_lyric_version_field_missing")

	#------------------------------
	# Running all hymn lyric tests
	# 
	# docker_run("music", "python manage.py test music.tests.hymn_lyric.test_hymn_lyric")



	# ------------------------------
	# SEARCH TESTS
	#

	#------------------------------
	# Running a specific search test
	# 
	# docker_run("music", "python manage.py test music.tests.search.test_search.SearchTests.test_search_for_artist_by_name")

	#------------------------------
	# Running all search tests
	# 
	# docker_run("music", "python manage.py test music.tests.search.test_search")


	#------------------------------
	# Running ALL tests
	# 
	docker_run("music", "python manage.py test music.tests")

def dev_test(service_name_list=None):
	print("Running development tests...")

	# dev_test_jubilo_auth()


	dev_test_jubilo_music()






	#------------------------------
	# Running ALL tests
	# 
	# docker_run("music", "python manage.py test music.tests")

COMMANDS = {
	"docker.build": docker_build,
	"docker.start": docker_start,
	"docker.stop": docker_stop,
	"docker.down": docker_down,
	"dev.setup": dev_setup,
	"dev.test": dev_test,
}

def main():
	parser = argparse.ArgumentParser(prog = "jubilo", description = "Jubilo CLI - Manage your Jubilo infrastructure with ease")

	parser.add_argument("group", help="Service group to manage")
	parser.add_argument("action", help="Action to perform on the service group")
	parser.add_argument("service_name_list", nargs="*", help="Specific services to target (optional)")

	args = parser.parse_args()

	command_key = f"{args.group}.{args.action}"

	if command_key not in COMMANDS:
		print(f"Unknown command: {command_key}")
		parser.print_help()
		return

	command = COMMANDS[command_key]

	try:
		command(args.service_name_list)
	except Exception as e:
		print(f"Error: {e}")


if __name__ == "__main__":
	main()